@url = http://localhost:8080


###
POST {{url}}/api/v1/nota/pdf-generator
Content-Type: application/json

{
    "codigo": 123,
    "cliente": {
        "codigo": 1036,
        "nome": "Thais",
        "endereco": "Rua ribeirão vermelho",
        "cep": 12345678,
        "bairro": "AQUELE",
        "cidade": "BELO HORIZONTE",
        "estado": "MG",
        "telefone": "333333333333",
        "inscest": "12121212121",
        "cnpjCpe": "12341234123412"
    },
    "produtosVendidos": [
        {
            "codigo": 1,
            "nome": "maça",
            "unidade": "PC",
            "quantidade": 1,
            "valor": 2.1
        },
        {
            "codigo": 2,
            "nome": "Pera",
            "unidade": "CX",
            "quantidade": 2,
            "valor": 0.9
        },
        {
            "codigo": 2,
            "nome": "Uva",
            "unidade": "CX",
            "quantidade": 3,
            "valor": 10.0
        }
    ],
    "formaDePagamento" : "DINHEIRO",
    "valorDaEntrada" : 15.5,
    "obs" : ""
}

